Users roles
AnyBlok/anyblok_furetui pull request #38
Opened 2020-11-24 16:38 UTC by petrus-v

2020-11-24 16:52 UTC, petrus-v commented on anyblok_furetui/auth/data/role_authorization_importer.py
> +    )
déplacer ça dans un enum ou autre

2020-11-24 16:59 UTC, petrus-v commented on anyblok_furetui/auth/data/role_authorization_importer.py
> +        for model, authz in config_callback().items():
hey man why a callback ?

2020-11-25 21:25 UTC, jssuzanne requested changes
need modification du of anyblok_pyramid

2020-12-03 15:01 UTC, merged

2020-12-03 15:01 UTC, jssuzanne commented
Thanks for all